productPage designupdate
Willen17/Hyrstacken pull request #40
Opened 2022-12-06 07:44 UTC by nybbe123

kolla productpage uppdateringar

2022-12-06 08:33 UTC, Willen17 requested changes
Snyggt med headern! Är lite småsaker som du behöver fixa, kolla över responsitivitet och lite annat.

2022-12-06 08:33 UTC, Willen17 commented on pages/searchResults.tsx
> +
Gör om detta till media-queries.

2022-12-06 08:33 UTC, Willen17 commented on pages/searchResults.tsx
> +                <h2 className="text-2xl font-bold">Resultat prylar</h2>
Search-bar-grejen lägger sig framför titeln på mindre skärmar. Arrow-back pilen har också försvunnit.

2022-12-07 09:50 UTC, Willen17 approved these changes
Allt ser bra ut, kung!

2022-12-07 10:05 UTC, Willen17 approved these changes
👍

2022-12-07 10:05 UTC, Willen17 approved these changes
work now

2022-12-07 10:06 UTC, Willen17 approved these changes
kung igen

2022-12-07 10:07 UTC, Willen17 approved these changes
approved

2022-12-07 10:07 UTC, matsegard approved these changes

2022-12-07 10:11 UTC, closed without merging